SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE DATABASE adminPanel;


CREATE TABLE `beehive` (
  `id` int(6) UNSIGNED NOT NULL,
  `icon` varchar(30) NOT NULL,
  `bg` varchar(30) NOT NULL,
  `title` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



INSERT INTO `beehive` (`id`, `icon`, `bg`, `title`) VALUES
(1, 'ah.png', 'albertheijn.jpg', 'Beehive#1'),
(2, 'jumbo_icon.jpg', 'jumbo.jpg', 'Beehive#2'),
(3, 'aldi_icon.png', 'aldi.png', 'Beehive#3');


ALTER TABLE `beehive`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `beehive`
  MODIFY `id` int(6) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
